### ISSUE TITLE
Segmentation fault when reading in bgzip compressed files

### ISSUE THREAD

**Issue by rozaimirazali** [winni2k/measureAggregateRsquared#1]
I ran the code earlier and it resulted in Segmentation Fault. But after uncompressing the Validation and Truth files in samples/v1.0/ , the code works fine. In the Github page, you mentioned that the imputed and validation files were output from Impute2, so I assumed both files were compressed with bgzip.
 
In Line 243 and 282, when reading the sample and validation input files respectively, is the code expecting to receive a compressed file or a binary file or just any string?

**Comment by winni2k** [comment]
Hey,
The `samples/v1.0` are not actually part of regression testing anymore, so I don't know if `measureAggregateRsquared` should actually work on those files. I will be removing them from the repo to avoid confusion.  Please instead test on the `samples/v2.0` files.  

The code below works for me, and the input gen files are compressed.  Please try this and let me know how it goes:

```bash
cd sample/v2.0
../../bin/measureAggregateRsquared --validation ALL.20130523.snps_indels.CGI.genotypes.nonGL.inRef.inGL.head1000.chr20.gen.gz --imputed ALL.20130523.snps_indels.CGI.genotypes.nonGL.inRef.inGL.inChip.impute2.notInChip.head500.chr20.gen.gz --sample CGI2.ILLU1M.sample --freq ALL.chr20.unionAC10NM.founders.B7.R1.P8.M30.K100.W500kb.inInt.inTruth.GL.head1000.freqs --bin olivierBins.txt --output tmp
```

**Comment by rozaimirazali** [comment]
Hi. The program is showing the following error message:

 Processing ... measureAggregateRsquared v0.12

Validation checked :	ALL.20130523.snps_indels.CGI.genotypes.nonGL.inRef.inGL.head1000.chr20.gen.gz
Imputed checked:	ALL.20130523.snps_indels.CGI.genotypes.nonGL.inRef.inGL.inChip.impute2.notInChip.head500.chr20.gen.gz
Sample checked:		CGI2.ILLU1M.sample
Frequencies checked:	ALL.chr20.unionAC10NM.founders.B7.R1.P8.M30.K100.W500kb.inInt.inTruth.GL.head1000.freqs
All inputs checked -- works fine
Bins:		olivierBins.txt
Output:		tmp

Reading samples description in [CGI2.ILLU1M.sample]
  * population column: 3
  * #pop=4
  * #ind=51
  * effectif= [AFR, 2] [AMR, 37] [ASN, 2] [EUR, 10]
Reading validation data in [ALL.20130523.snps_indels.CGI.genotypes.nonGL.inRef.inGL.head1000.chr20.gen.gz]
Segmentation fault

I suspect the reason is that when I was compiling the code, there were some issues with boost and zlib.  I will raise a new issue and explain it there

**Comment by winni2k** [comment]
Ok, let's continue this conversation in #3
