### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by rozaimirazali** [winni2k/measureAggregateRsquared#2]
Please correct me if I am wrong, but the headers for the output file are

Bin_frequency	r_square	num_genotypes	freq_validation	freq_imputation

But is the code really printing the number of genotypes under the num_genotypes or the number of variants? 

Also, the Bin_frequency column does not show the boundaries that are set in the --bin file but the result that is printed to stdout do show the number of genotypes.

**Comment by winni2k** [comment]
The `num_genotypes` column is actually the number of sites that were analyzed.

The `bin_frequency` column is the average frequency of each bin. From reading the code, I am pretty sure that the frequency is the frequency of the validation variants.

**Comment by abiddanda54gene** [comment]
Realizing that this is closed, but could it be added to the README for clearer documentation at the offset?

**Comment by winni2k** [comment]
Sure, pull requests are welcome.
