### ISSUE TITLE
Issues relating to compilation of the makefile

### ISSUE THREAD

**Issue by rozaimirazali** [winni2k/measureAggregateRsquared#3]
was not able to detect the path to Boost despite pointing to it in the file. This was the error message.

> In file included from src/utils.cpp:1:0:
> src/utils.h:35:48: fatal error: boost/iostreams/filtering_stream.hpp: No such file or directory
>  #include <boost/iostreams/filtering_stream.hpp>

It seems that the variable containing the path to boost is not passed correctly so we had to manually change them in the codes.

Then, when we re-compiled the makefile, it gave a new error saying something about not detecting the path to z and bz2 despite both of them being in the $PATH. So we ran the following command:

`g++ -std=c++11 -DNDEBUG  obj/utils.o obj/measureAggregateRsquared.o /gpfs/software/tools/boost/1.54.0/lib/libboost_iostreams.a /gpfs/software/tools/boost/1.54.0/lib/libboost_program_options.a -o bin/measureAggregateRsquared -O3 -lm -lpthread -lz -lbz2`

I'm not sure if it compiled successfully because there were still some error messages about bzip (sorry, I will paste them later. not currently in front of my desk).

When I ran the samples, the program seems to work fine if I uncompressed the .gen files. But if I use the compressed .gen files (regardless of the samples), it throws segmentation fault error message.

**Comment by winni2k** [comment]
This code relies on boost to unzip the gen files. If boost is not being linked in correctly, then that would explain why the unzipping does not work :/

What system are you compiling under? The only system I have managed to compile this code under is Debian and CentOS linux.

**Comment by winni2k** [comment]
Also, my understanding of nix systems (I assume you're running on a nix system?) is that linkers do not use `$PATH`.  Instead they use `LD_LIBRARY_PATH`.  Check out [this link](https://stackoverflow.com/questions/16044020/gcc-and-linking-environment-variables-and-flags#16047559) for more information.

**Comment by winni2k** [comment]
To figure out what libraries are being linked into the binary, you can use `ldd binary_file` on a Linux system.
