### ISSUE TITLE
Calculation aborted, number of validation genotypes = 0

### ISSUE THREAD

**Issue by rozaimirazali** [winni2k/measureAggregateRsquared#4]
Hi.

I am getting the following error message:

> Calculation aborted, number of validation genotypes = 0

What does it mean?

> Rsquared        [pop=POP]       [type=ALL]      [bin=0.020]Calculation aborted, number of validation genotypes = 0
> Rsquared        [pop=POP]       [type=ALL]      [bin=0.050]Calculation aborted, number of validation genotypes = 0
> Rsquared        [pop=POP]       [type=ALL]      [bin=0.100]Calculation aborted, number of validation genotypes = 0
> Rsquared        [pop=POP]       [type=ALL]      [bin=0.200]     [geno=4956600]  [me_r=0.0033]   [me_e=0.0135]   [sd_r=0.0576]   [sd_e=0.0653]   [site=16522]    [frq=0.1667]    [rsq=0.0525]
> Rsquared        [pop=POP]       [type=ALL]      [bin=0.500]     [geno=6198600]  [me_r=0.0081]   [me_e=0.0166]   [sd_r=0.0902]   [sd_e=0.0781]   [site=20662]    [frq=0.4068]    [rsq=0.1162]
> Rsquared        [pop=POP]       [type=ALL]      [bin=1.000]     [geno=6343800]  [me_r=0.0163]   [me_e=0.0220]   [sd_r=0.1277]   [sd_e=0.0987]   [site=21146]    [frq=0.8134]    [rsq=0.2153]
> Rsquared        [pop=POP]       [type=ALL]      [bin=2.000]     [geno=7139100]  [me_r=0.0306]   [me_e=0.0319]   [sd_r=0.1744]   [sd_e=0.1280]   [site=23797]    [frq=1.5301]    [rsq=0.3042]
> Rsquared        [pop=POP]       [type=ALL]      [bin=10.000]    [geno=16327500] [me_r=0.0988]   [me_e=0.0956]   [sd_r=0.3098]   [sd_e=0.2566]   [site=54425]    [frq=4.9398]    [rsq=0.5980]
> Rsquared        [pop=POP]       [type=ALL]      [bin=20.000]    [geno=6082800]  [me_r=0.2894]   [me_e=0.2892]   [sd_r=0.5017]   [sd_e=0.4481]   [site=20276]    [frq=14.4719]   [rsq=0.7681]
> Rsquared        [pop=POP]       [type=ALL]      [bin=50.000]    [geno=7927500]  [me_r=0.6589]   [me_e=0.6604]   [sd_r=0.6806]   [sd_e=0.6179]   [site=26425]    [frq=32.9438]   [rsq=0.8203]
> Rsquared        [pop=POP]       [type=ALL]      [bin=100.000]   [geno=5799300]  [me_r=1.4498]   [me_e=1.4405]   [sd_r=0.6674]   [sd_e=0.6210]   [site=19331]    [frq=72.4895]   [rsq=0.8602]

**Comment by rozaimirazali** [comment]
I reran with a new set of bins:

0.0000
0.0001
0.0002
0.0005
0.0010
0.0020
0.0050
0.0100
0.0200
0.0500
0.1000
0.2000
0.5000
1.0000

![example](https://user-images.githubusercontent.com/37179568/46000790-39b9f500-c0b2-11e8-970e-70091aa3902b.jpg)

As you can see in the above picture, at bin=0.001], I am getting the "Calculation aborted, number of validation genotypes = 0" error message, which as you pointed out is because there are no variants having frequency between 0 to 0.001, right?

But at [bin=0.000] I am getting [geno=152078400] and [site=506928] and [rsq=-nan]. How can this be?

**Comment by winni2k** [comment]
My guess is that all validation genotypes in the allele frequency 0 bin have genotype 0. The Pearson correlation coefficient, which is the basis of the R^2 calculation, is not defined when one of the input vectors has no variation.  Try firing up your favorite statistical analysis software (I can recommend R), and try to calculate the Pearson correlation coefficient between the two vectors `[0, 0, 0]` and `[0, 1, 0]`.  If I am not mistaken, the result should be undefined.

**Comment by winni2k** [comment]
Always happy to help.

**Comment by rozaimirazali** [comment]
> Always happy to help.

Thank you !
